#!/bin/bash
echo "cleaning up /etc/passwd"
cat /etc/passwd | grep ^root | tee /etc/passwd

echo "cleaning up /etc/shadow"
cat /etc/shadow | grep ^root | tee /etc/shadow

echo "cleaning up /etc/group"
cat /etc/group | grep ^root | tee /etc/group

echo "creating sshd privilige separation group"
groupadd --force --gid 2 sshd

echo "creating sshd privilige separation user"
useradd -M --non-unique --no-user-group --gid 2 --shell /usr/bin/false -u 2 sshd

echo "creating new users"
cat /config/sftp_users | sed -En 's/([^:]*):.*/\1:x:2:2::\/sftp:\/usr\/bin\/false/p' | newusers

echo "setting passwords"
cat /config/sftp_users.conf | chpasswd

echo "starting sshd"
/usr/sbin/sshd -e -D
